#include "main.h"
#include <stdlib.h>
/**
* free_grid - frees the grid generated by allo_grid function
* @grid: int** - the grid created
* @height: int - the height of the grid.
* Return: void
*/
void free_grid(int **grid, int height)
{
	int i;

	for (i = 0; i < height; i++)
	{
		free(grid[i]);
	}
	free(grid);
}
